# -*- coding: utf-8 -*-
# Generated by Django 3.0.6 on 2020-05-25 06:46

from django.db import migrations, models
from django.conf import settings

import requests
import json
import unicodedata


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Produits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=5024,default="nc", blank=True)),
                ('url_image_ingredients', models.URLField(max_length=5024,default="nc", blank=True)),
                ('brands_tags', models.CharField(max_length=500)),
                ('grade', models.CharField(max_length=500,default="nc", blank=True, null=True)),
                ('image_front_url', models.URLField(max_length=5024,default="nc", blank=True)),
                ('image_nutrition_url', models.URLField(max_length=5024,default="nc", blank=True)),
                ('nova_groups', models.CharField(max_length=500,default="nc", blank=True)),
                ('generic_name_fr', models.CharField(max_length=500)),
                ('url_site', models.URLField(max_length=5024)),
                ('ingredients_text_fr', models.CharField(max_length=5024)),
                ('_id', models.FloatField()),

            ],
            options={
                'db_table': 'app_produits',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=5024)),
                ('nom_iaccents', models.CharField(max_length=5024)),
                ('produit', models.ManyToManyField('Produits')),

            ],
            options={
                'db_table': 'app_categories',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vendeurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produits', models.ForeignKey('Produits', on_delete=models.CASCADE)),
                ('nom', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'app_vendeurs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Nutriments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produits', models.ForeignKey('Produits', on_delete=models.CASCADE)),
                ('nom', models.CharField(max_length=5000)),
                ('unite', models.CharField(max_length=10)),
                ('valeur', models.FloatField())
            ],
            options={
                'db_table': 'app_nutriments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Favoris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)),
                ('produits', models.ForeignKey('Produits', on_delete=models.CASCADE)),
                ('date_ajout', models.DateField(auto_now_add=True)),
                ('aff_index', models.BooleanField()),
            ],
            options={
                'db_table': 'app_favoris',
                'managed': True,
            },
        ),
    ]
