# Generated by Django 3.0.6 on 2020-05-26 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateurs',
            name='id_comptes',
        ),
        migrations.DeleteModel(
            name='Comptes',
        ),
        migrations.DeleteModel(
            name='Utilisateurs',
        ),
    ]
