# Generated by Django 3.0.6 on 2020-06-03 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoris',
            options={},
        ),
        migrations.AlterModelOptions(
            name='nutriments',
            options={},
        ),
        migrations.AlterModelOptions(
            name='produits',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vendeurs',
            options={},
        ),
        migrations.AddField(
            model_name='favoris',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='favoris',
            name='aff_index',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='nutriments',
            name='nom',
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name='produits',
            name='brands_tags',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='produits',
            name='generic_name_fr',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='produits',
            name='grade',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='produits',
            name='image_front_url',
            field=models.URLField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='produits',
            name='image_nutrition_url',
            field=models.URLField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='produits',
            name='ingredient',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='produits',
            name='ingredients_text_fr',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='produits',
            name='nova_groups',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='produits',
            name='url_image_ingredients',
            field=models.URLField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='produits',
            name='url_site',
            field=models.URLField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='vendeurs',
            name='nom',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterModelTable(
            name='favoris',
            table=None,
        ),
        migrations.AlterModelTable(
            name='nutriments',
            table=None,
        ),
        migrations.AlterModelTable(
            name='produits',
            table=None,
        ),
        migrations.AlterModelTable(
            name='vendeurs',
            table=None,
        ),
    ]
