# Generated by Django 3.0.6 on 2020-05-29 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OCprojetHuit', '0002_auto_20200526_1435'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favoris',
        ),
    ]
