# Generated by Django 3.0.6 on 2020-05-29 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OCprojetHuit', '0003_delete_favoris'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favoris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateField(auto_now_add=True)),
                ('aff_index', models.BooleanField()),
                ('produits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Produits')),
            ],
        ),
    ]
