# Generated by Django 3.0.6 on 2020-05-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OCprojetHuit', '0004_favoris'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoris',
            name='aff_index',
            field=models.BooleanField(default=False),
        ),
    ]
